window.LANGBIANG_FITMENTS = [
  {
    line: "sprockets",
    sku: "LGF-YAM-WR155-520-13T",
    productSlug: "front-sprocket-42crmo4",
    product: "42CrMo4 Race Steel Front Sprocket",
    brand: "Yamaha",
    model: "WR155R",
    year: "2020-2026",
    type: "520 conversion",
    material: "42CrMo4 Race Steel",
    position: "Front",
    toothCount: "13T",
    price: "Price on request",
    detail:
      "Front 520 conversion sample for WR155R. Confirm spline profile, retaining plate, chain width, and case clearance."
  },
  {
    line: "sprockets",
    sku: "LGR-YAM-WR155-520-48T-42CR",
    productSlug: "rear-sprocket-42crmo4",
    product: "42CrMo4 Race Steel Rear Sprocket",
    brand: "Yamaha",
    model: "WR155R",
    year: "2020-2026",
    type: "520 conversion",
    material: "42CrMo4 Race Steel",
    position: "Rear",
    toothCount: "48T",
    price: "Price on request",
    detail: "Race steel rear 520 conversion sample for WR155R. Confirm hub pattern, chain line, and guide clearance."
  },
  {
    line: "sprockets",
    sku: "LGR-YAM-WR155-520-50T-7075",
    productSlug: "rear-sprocket-7075",
    product: "7075-T6 Race Aluminum Rear Sprocket",
    brand: "Yamaha",
    model: "WR155R",
    year: "2020-2026",
    type: "520 conversion",
    material: "7075-T6 Aluminum",
    position: "Rear",
    toothCount: "50T",
    price: "Price on request",
    detail: "7075-T6 rear sample for lower rotating mass. Confirm hub pattern, chain line, and guide clearance."
  },
  {
    line: "sprockets",
    sku: "LGF-KTM-SXF450-520-13T",
    productSlug: "front-sprocket-42crmo4",
    product: "42CrMo4 Race Steel Front Sprocket",
    brand: "KTM",
    model: "450 SX-F",
    year: "2016",
    type: "Race fitment",
    material: "42CrMo4 Race Steel",
    position: "Front",
    toothCount: "13T",
    price: "Price on request",
    detail: "Front race fitment sample for KTM 450 SX-F. Confirm spline and chain clearance before ordering."
  },
  {
    line: "brake-rotor",
    sku: "LGBR-KTM-SXF450-F-260",
    productSlug: "front-brake-rotor",
    product: "Front Brake Rotor",
    brand: "KTM",
    model: "450 SX-F",
    year: "2016",
    type: "Front rotor",
    material: "SUS420 / rotor-grade stainless by batch",
    diameter: "260 mm sample",
    price: "Price on request",
    detail: "Front brake rotor sample for heat, mud, braking load, and flatness check by batch."
  },
  {
    line: "brake-rotor",
    sku: "LGBR-KTM-SXF450-R-220",
    productSlug: "rear-brake-rotor",
    product: "Rear Brake Rotor",
    brand: "KTM",
    model: "450 SX-F",
    year: "2016",
    type: "Rear rotor",
    material: "SUS420 / rotor-grade stainless by batch",
    diameter: "220 mm sample",
    price: "Price on request",
    detail: "Rear brake rotor sample for mud, heat, braking feel, and fitment-based replacement."
  },
  {
    line: "brake-rotor",
    sku: "LGBR-HON-CRF150L-F",
    productSlug: "front-brake-rotor",
    product: "Front Brake Rotor",
    brand: "Honda",
    model: "CRF150L",
    year: "2017-2025",
    type: "Front rotor",
    material: "Rotor-grade stainless by batch",
    price: "Price on request",
    detail: "Front brake rotor sample for CRF150L. Confirm diameter, bolt circle, offset, and caliper clearance."
  },
  {
    line: "cnc-performance",
    sku: "LGCNC-YAM-YZ250-CLUTCH",
    productSlug: "billet-clutch-cover",
    product: "Billet Clutch Cover",
    brand: "Yamaha",
    model: "YZ250",
    year: "2005-2024 sample",
    type: "Clutch cover",
    material: "Billet aluminum by batch",
    application: "Clutch cover",
    price: "Price on request",
    detail: "CNC billet clutch cover sample. Confirm cover shape, bolt pattern, gasket surface, and oil clearance."
  },
  {
    line: "cnc-performance",
    sku: "LGCNC-KTM-EXC-WP-COVER",
    productSlug: "water-pump-cover",
    product: "Water Pump Cover",
    brand: "KTM",
    model: "EXC",
    year: "2017-2023 sample",
    type: "Water pump cover",
    material: "Billet aluminum by batch",
    application: "Water pump cover",
    price: "Price on request",
    detail: "CNC water pump cover sample. Confirm coolant clearance, gasket surface, bolt pattern, and model year."
  },
  {
    line: "cnc-performance",
    sku: "LGCNC-YAM-YZ250-SIDE",
    productSlug: "engine-side-cover",
    product: "Engine Side Cover",
    brand: "Yamaha",
    model: "YZ250",
    year: "2005-2024 sample",
    type: "Engine side cover",
    material: "Billet aluminum by batch",
    application: "Engine side cover",
    price: "Price on request",
    detail: "CNC engine side cover sample. Confirm cover profile, sealing surface, bolt pattern, and heat exposure."
  },
  {
    line: "bolt-kits",
    sku: "LGTI-KTM-SXF450-ROTOR",
    productSlug: "rotor-bolt-set",
    product: "Grade 5 Titanium Rotor Bolt Set",
    brand: "KTM",
    model: "450 SX-F",
    year: "2016",
    type: "Rotor bolt set",
    material: "Grade 5 Titanium / Ti-6Al-4V",
    application: "Rotor bolt set",
    price: "Price on request",
    detail: "Measured rotor bolt set sample. Verify thread, length, shoulder, washer, torque, and heat exposure."
  },
  {
    line: "bolt-kits",
    sku: "LGTI-YAM-WR155-SPROCKET",
    productSlug: "sprocket-bolt-set",
    product: "Grade 5 Titanium Sprocket Bolt Set",
    brand: "Yamaha",
    model: "WR155R",
    year: "2020-2026",
    type: "Sprocket bolt set",
    material: "Grade 5 Titanium / Ti-6Al-4V",
    application: "Sprocket bolt set",
    price: "Price on request",
    detail: "Measured sprocket bolt set sample. Verify thread, washer stack, shoulder, torque, and hub clearance."
  },
  {
    line: "bolt-kits",
    sku: "LGTI-RACE-UNIVERSAL-MEASURED",
    productSlug: "measured-race-hardware-kit",
    product: "Measured Grade 5 Titanium Race Hardware Kit",
    brand: "Universal / measured",
    model: "By measurement",
    year: "By measurement",
    type: "Measured hardware kit",
    material: "Grade 5 Titanium / Ti-6Al-4V",
    application: "Measured hardware kit",
    price: "Price on request",
    detail: "Measured Grade 5 titanium hardware kit. Application must be verified before production or installation."
  }
];
